development:
  host: localhost
  database: asakusa_satellite_development

test:
  host: localhost
  database: asakusa_satellite_test

production:
  host: <%= ENV['MONGODB_HOST'] %>
  port: <%= ENV['MONGODB_PORT'] %>
  database: <%= ENV['MONGODB_DATABASE'] %>
  username: <%= ENV['MONGODB_USERNAME'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
