oauth_request_token: "Ug9FZ0r8zp3jwuvOGFYWQ"
oauth_request_token_secret: "qMvcOzyQu4Qkz1bm0k1bOHYDn1m4JF3DXbQK9CWfMA"
oauth_request_site: "http://twitter.com"
#login_link : "redmineauth"
#login_link_redmine: Redmine URL

# file attachment setting for local storage
attachment_path: "public/upload"
# file attachment setting for heroku temporary directory
# attachment_path: "tmp"
