omniauth:
  provider: "twitter"
  provider_args:
    - "Ug9FZ0r8zp3jwuvOGFYWQ"
    - "qMvcOzyQu4Qkz1bm0k1bOHYDn1m4JF3DXbQK9CWfMA"

#login_link : "redmineauth"
#login_link_redmine: Redmine URL

# file attachment
attachment_policy: <%= ENV['SETTINGS_ATTACHMENT_POLICY'] || "local" %>
attachment_path: <%= ENV['SETTINGS_ATTACHMENT_PATH'] || "public/upload" %>
watage_token: <%= ENV['SETTINGS_WATAGE_ACCESS_TOKEN'] || "00000000-0000-0000-0000-000000000000" %>
watage_token_secret: <%= ENV['SETTINGS_WATAGE_ACCESS_TOKEN_SECRET'] || "00000000-0000-0000-0000-000000000000" %>
